export const cityForecasts = [
  {
    city: 'Tokyo',
    country: 'Japan',
    flag: '🇯🇵',
    temperature: 22,
    condition: 'Clear',
    high: 25,
    low: 18,
    humidity: 61,
    wind: 14,
    localTime: '06:45',
    accent: 'sunrise',
    summary: 'Warm sunrise with crisp air and excellent visibility.',
  },
  {
    city: 'Jakarta',
    country: 'Indonesia',
    flag: '🇮🇩',
    temperature: 31,
    condition: 'Humid Clouds',
    high: 33,
    low: 27,
    humidity: 79,
    wind: 10,
    localTime: '04:45',
    accent: 'tropic',
    summary: 'Heavy moisture in the air with soft afternoon cloud cover.',
  },
  {
    city: 'Los Angeles',
    country: 'United States',
    flag: '🇺🇸',
    temperature: 26,
    condition: 'Sunny',
    high: 29,
    low: 17,
    humidity: 48,
    wind: 9,
    localTime: '14:45',
    accent: 'coast',
    summary: 'Bright and dry with a calm Pacific breeze through downtown.',
  },
  {
    city: 'Havana',
    country: 'Cuba',
    flag: '🇨🇺',
    temperature: 28,
    condition: 'Partly Cloudy',
    high: 30,
    low: 24,
    humidity: 73,
    wind: 12,
    localTime: '17:45',
    accent: 'coral',
    summary: 'Late-day warmth with scattered clouds and gentle coastal wind.',
  },
  {
    city: 'Lisbon',
    country: 'Portugal',
    flag: '🇵🇹',
    temperature: 19,
    condition: 'Breezy',
    high: 21,
    low: 15,
    humidity: 58,
    wind: 18,
    localTime: '22:45',
    accent: 'atlantic',
    summary: 'Cool Atlantic air keeps the evening comfortable and bright.',
  },
];

export const landingHighlights = [
  'Live-inspired global city weather snapshots',
  'Elegant cards designed for future API integration',
  'Responsive layout for desktop, tablet, and mobile',
];
